
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyspaszcchdknujhwpfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5c3Bhc3pjY2hka251amh3cGZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1ODI2NjIsImV4cCI6MjA1ODE1ODY2Mn0.zl2ZzTWBQkfsplgj0AI-u_UPck1z81ez6s5CsghmhNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true
  },
  global: {
    headers: {
      'X-Client-Info': 'music-portal-app'
    }
  }
});

// Add explicitly typed functions for RPC calls to ensure TypeScript correctly recognizes them
export const rpcFunctions = {
  checkSongExists: (title: string, artist: string) => 
    supabase.rpc('check_song_exists', { _title: title, _artist: artist })
      .then(result => {
        if (result.error) throw result.error;
        return result.data as boolean;
      }),
  incrementSongView: (songId: string) =>
    supabase.rpc('increment_song_view', { _song_id: songId })
}
